Add error trapping

diff --git a/bin/switch b/bin/switch
--- a/bin/switch
+++ b/bin/switch
@@ -1,5 +1,13 @@
 #!/usr/bin/env zsh
 
+error() {
+    revolver stop
+    echo "Error occured while switching connection!"
+    exit 1
+}
+
+trap error ERR
+
 # Get sudo privileges immediatly
 sudo echo > /dev/null
 
@@ -9,19 +17,19 @@ my_interface=$(ip route get 8.8.8.8 | awk '/dev/ {f=NR} f&&NR-1==f' RS=" ")
 
 adsl() {
     revolver start "Switching connection to ADSL"
-    sudo ip addr del 192.168.2.27/24 dev "$my_interface"
+    sudo ip addr del 192.168.2.27/24 dev "$my_interface" > /dev/null 2>&1 || true
     sudo ip addr add 192.168.2.28/24 broadcast 192.168.2.255 dev "$my_interface"
     sudo ip route add default via 192.168.2.3
-    sleep 0.5
+    sleep 1
     revolver stop
 }
 
 lte() {
     revolver start "Switching connection to LTE"
-    sudo ip addr del 192.168.2.28/24 dev "$my_interface"
+    sudo ip addr del 192.168.2.28/24 dev "$my_interface" > /dev/null 2>&1 || true
     sudo ip addr add 192.168.2.27/24 broadcast 192.168.2.255 dev "$my_interface"
     sudo ip route add default via 192.168.2.3
-    sleep 0.5
+    sleep 1
     revolver stop
 }
 
@@ -40,5 +48,5 @@ elif [ "$1" = "" ]; then
     fi
 else
     echo "Unknown option: $1"
-    echo "Available options: adsl, lte"
+    echo "Available options: adsl, lte or none (will switch between adsl and lte)"
 fi
